/* closures.c generated by valac 0.40.8, the Vala compiler
 * generated from closures.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <stdio.h>

typedef struct _Block1Data Block1Data;

typedef void (*MyFunction) (gint a, gpointer user_data);
struct _Block1Data {
	int _ref_count_;
	gint b;
	gint c;
};



void caller (MyFunction f,
             gpointer f_target);
void _vala_main (void);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda4_ (Block1Data* _data1_,
                 gint a);
static void ___lambda4__my_function (gint a,
                              gpointer self);
static void __lambda5_ (Block1Data* _data1_,
                 gint a);
static void ___lambda5__my_function (gint a,
                              gpointer self);


void
caller (MyFunction f,
        gpointer f_target)
{
	f (3, f_target);
}


static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		g_slice_free (Block1Data, _data1_);
	}
}


static void
__lambda4_ (Block1Data* _data1_,
            gint a)
{
	FILE* _tmp0_;
	_data1_->c = 4;
	_data1_->b = 5;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "%d %d\n", a, _data1_->c);
}


static void
___lambda4__my_function (gint a,
                         gpointer self)
{
	__lambda4_ (self, a);
}


static void
__lambda5_ (Block1Data* _data1_,
            gint a)
{
	FILE* _tmp0_;
	_data1_->b = 4;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "%d %d\n", a, _data1_->b);
}


static void
___lambda5__my_function (gint a,
                         gpointer self)
{
	__lambda5_ (self, a);
}


void
_vala_main (void)
{
	Block1Data* _data1_;
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->b = 3;
	_data1_->c = 4;
	caller (___lambda4__my_function, _data1_);
	caller (___lambda5__my_function, _data1_);
	block1_data_unref (_data1_);
	_data1_ = NULL;
}


int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}



